#!/usr/bin/env node

/**
 * Generate Design Tokens Script
 * Converts JSON design tokens to CSS custom properties with proper naming
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.join(__dirname, '..');

console.log('🎨 Generating design tokens...\n');

try {
  // Run style-dictionary to generate CSS custom properties
  execSync('npm run build:tokens', {
    cwd: projectRoot,
    stdio: 'inherit',
  });

  // Post-process the CSS to fix naming
  const cssPath = path.join(
    projectRoot,
    'src/styles/tokens/tokens.css'
  );
  let cssContent = fs.readFileSync(cssPath, 'utf8');

  const normalizeValue = (value) => {
    const trimmed = value.trim();
    const remMatch = trimmed.match(/^-?\d+(?:\.\d+)?rem$/i);
    const pxMatch = trimmed.match(/^-?\d+(?:\.\d+)?px$/i);

    if (remMatch || pxMatch) {
      const unit = trimmed.endsWith('rem') ? 'rem' : 'px';
      const numeric = parseFloat(trimmed.replace(unit, ''));

      if (!Number.isNaN(numeric)) {
        const rounded = Number(numeric.toFixed(4));
        return `${rounded}${unit}`;
      }
    }

    return trimmed;
  };

  const buildTailwindTheme = (variables) => {
    const theme = {
      colors: {},
      spacing: {},
      fontSize: {},
      borderRadius: {},
    };

    for (const [token, value] of Object.entries(variables)) {
      if (token.startsWith('color-')) {
        theme.colors[token.replace('color-', '')] = value;
      } else if (token.startsWith('spacing-')) {
        theme.spacing[token.replace('spacing-', '')] = value;
      } else if (token.startsWith('font-size-')) {
        theme.fontSize[token.replace('font-size-', '')] = value;
      } else if (token.startsWith('border-radius-')) {
        theme.borderRadius[token.replace('border-radius-', '')] = value;
      }
    }

    return Object.fromEntries(
      Object.entries(theme).filter(([, values]) => Object.keys(values).length > 0)
    );
  };

  const buildDaisyThemes = (variables) => {
    const theme = {};
    const assignFromToken = (key, token) => {
      if (variables[token]) {
        theme[key] = variables[token];
      }
    };

    assignFromToken('primary', 'color-powerfull-blue');
    assignFromToken('primary-content', 'color-white');
    assignFromToken('secondary', 'color-powerfull-orange');
    assignFromToken('secondary-content', 'color-white');
    assignFromToken('accent', 'color-powerfull-orange');
    assignFromToken('neutral', 'color-dark');
    assignFromToken('neutral-content', 'color-white');
    assignFromToken('base-100', 'color-white');
    assignFromToken('base-200', 'color-dark');
    assignFromToken('base-300', 'color-dark');
    assignFromToken('base-content', 'color-dark');
    assignFromToken('info', 'color-powerfull-blue');
    assignFromToken('success', 'color-powerfull-blue');
    assignFromToken('warning', 'color-powerfull-orange');
    assignFromToken('error', 'color-powerfull-orange');
    assignFromToken('--rounded-box', 'border-radius-md');
    assignFromToken('--rounded-btn', 'border-radius-sm');
    assignFromToken('--rounded-badge', 'border-radius-sm');

    return [
      {
        qalim: theme,
      },
    ];
  };

  const writeTailwindThemeModule = (variables) => {
    const tailwindTheme = buildTailwindTheme(variables);
    const daisyThemes = buildDaisyThemes(variables);
    const themeDir = path.join(projectRoot, 'src/styles/tokens');
    const themePath = path.join(themeDir, 'tailwind-theme.mjs');
    const fileContent = `// Auto-generated by scripts/generate-tokens.js. Do not edit directly.\nexport const tailwindTheme = ${JSON.stringify(
      tailwindTheme,
      null,
      2
    )};\n\nexport const daisyThemes = ${JSON.stringify(
      daisyThemes,
      null,
      2
    )};\n`;

    fs.writeFileSync(themePath, fileContent);
    return themePath;
  };

  // Fix variable naming to be more consistent first
  cssContent = cssContent
    // Convert camelCase to kebab-case for all variables
    .replace(/--([a-z]+)([A-Z][a-z]*)/g, (match, first, rest) => {
      return `--${first}-${rest.toLowerCase()}`;
    })
    // Handle multiple camelCase words
    .replace(
      /--([a-z]+)-([a-z]+)([A-Z][a-z]*)/g,
      (match, first, second, rest) => {
        return `--${first}-${second}-${rest.toLowerCase()}`;
      }
    )
    // Fix specific naming patterns
    .replace(/--marquee-font-size-mobile/g, '--marquee-font-size-mobile')
    .replace(/--marquee-font-size-desktop/g, '--marquee-font-size-desktop')
    .replace(
      /--marquee-background-color-brand/g,
      '--marquee-background-color-brand'
    )
    .replace(/--marquee-font-color-brand/g, '--marquee-font-color-brand')
    .replace(
      /--marquee-border-radius-desktop/g,
      '--marquee-border-radius-desktop'
    )
    .replace(
      /--marquee-border-radius-mobile/g,
      '--marquee-border-radius-mobile'
    )
    .replace(/--border-radius-md/g, '--border-radius-md')
    .replace(/--border-radius-sm/g, '--border-radius-sm')
    .replace(/--font-size-xs/g, '--font-size-xs')
    .replace(/--font-size-sm/g, '--font-size-sm')
    .replace(/--font-size-xxs/g, '--font-size-xxs')
    .replace(/--font-size-md/g, '--font-size-md')
    .replace(/--font-size-lg/g, '--font-size-lg')
    .replace(/--font-size-xl/g, '--font-size-xl')
    // Add prefixes for better organization
    .replace(/--powerfull-orange/g, '--color-powerfull-orange')
    .replace(/--dark/g, '--color-dark')
    .replace(/--white/g, '--color-white')
    .replace(/--powerfull-blue/g, '--color-powerfull-blue')
    .replace(/--xs/g, '--spacing-xs')
    .replace(/--md/g, '--spacing-md')
    .replace(/--3xl/g, '--spacing-3xl')
    .replace(/--4xl/g, '--spacing-4xl')
    .replace(/--2xl/g, '--spacing-2xl')
    .replace(/--lg/g, '--spacing-lg')
    .replace(/--xxs/g, '--spacing-xxs')
    .replace(/--xl/g, '--spacing-xl')
    .replace(/--5xl/g, '--spacing-5xl')
    .replace(/--sm/g, '--spacing-sm');

  // Function to convert px values to rem (assuming 16px = 1rem)
  function convertToRem(cssContent) {
    return (
      cssContent
        // Convert spacing values to rem
        .replace(
          /--spacing-([^:]+):\s*(\d+(?:\.\d+)?)px/g,
          (match, name, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--spacing-${name}: ${remValue}rem`;
          }
        )
        // Convert font-size values to rem
        .replace(
          /--font-size-([^:]+):\s*(\d+(?:\.\d+)?)px/g,
          (match, name, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--font-size-${name}: ${remValue}rem`;
          }
        )
        // Convert border-radius values to rem (but keep border properties in px)
        .replace(
          /--border-radius-([^:]+):\s*(\d+(?:\.\d+)?)(?!px)/g,
          (match, name, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--border-radius-${name}: ${remValue}rem`;
          }
        )
        // Convert marquee border-radius values to rem
        .replace(
          /--marquee-border-radius([^:]+):\s*(\d+(?:\.\d+)?)(?!px)/g,
          (match, name, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--marquee-border-radius${name}: ${remValue}rem`;
          }
        )
        // Convert marquee font-size values to rem
        .replace(
          /--marquee-font-size([^:]+):\s*(\d+(?:\.\d+)?)px/g,
          (match, name, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--marquee-font-size${name}: ${remValue}rem`;
          }
        )
        // Convert marquee item gap values to rem
        .replace(
          /--marquee-item-gap:\s*(\d+(?:\.\d+)?)px/g,
          (match, value) => {
            const remValue = (parseFloat(value) / 16).toFixed(4);
            return `--marquee-item-gap: ${remValue}rem`;
          }
        )
    );
  }

  // Convert values to rem after naming fixes
  cssContent = convertToRem(cssContent);

  // Write the improved CSS
  fs.writeFileSync(cssPath, cssContent);

  const variableRegex = /--([a-z0-9-]+):\s*([^;]+);/gi;
  const tokens = {};
  let match;

  while ((match = variableRegex.exec(cssContent))) {
    const [, tokenName, tokenValue] = match;
    tokens[tokenName] = normalizeValue(tokenValue);
  }

  const tailwindThemePath = writeTailwindThemeModule(tokens);

  console.log('✅ Design tokens generated successfully!');
  console.log('📁 Output: src/styles/tokens/tokens.css');
  console.log(`🌀 Tailwind theme synced: ${path.relative(projectRoot, tailwindThemePath)}`);
  console.log(
    '🔄 Converted spacing, font-size, and border-radius to rem units'
  );
  console.log('📏 Border properties remain in pixels for precision');
  console.log('🌐 Tokens are globally available in all SCSS files');
  console.log('\n💡 Use directly in any SCSS file:');
  console.log('   color: var(--color-powerfull-blue);');
  console.log('   padding: var(--spacing-md); /* now in rem */');
  console.log('   font-size: var(--font-size-lg); /* now in rem */');
  console.log('   border-radius: var(--border-radius-md); /* now in rem */');
} catch (error) {
  console.error('❌ Token generation failed:', error.message);
  process.exit(1);
}
