/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  marquee: {
    "font-size": {
      mobile: {
        key: "{marquee.font-size.mobile}",
        $value: "16px",
        $type: "fontSizes",
        $description: "",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{font-size.xs}",
          $type: "fontSizes",
          $description: "",
          key: "{marquee.font-size.mobile}",
        },
        name: "marqueeFontSizeMobile",
        attributes: {
          category: "marquee",
          type: "font-size",
          item: "mobile",
        },
        path: ["marquee", "font-size", "mobile"],
      },
      desktop: {
        key: "{marquee.font-size.desktop}",
        $value: "25.888px",
        $type: "fontSizes",
        $description: "",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{font-size.sm}",
          $type: "fontSizes",
          $description: "",
          key: "{marquee.font-size.desktop}",
        },
        name: "marqueeFontSizeDesktop",
        attributes: {
          category: "marquee",
          type: "font-size",
          item: "desktop",
        },
        path: ["marquee", "font-size", "desktop"],
      },
    },
    "background-color": {
      brand: {
        key: "{marquee.background-color.brand}",
        $value: "#3200f2",
        $type: "color",
        $description: "branding bg-color",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{powerfull-blue}",
          $type: "color",
          $description: "branding bg-color",
          key: "{marquee.background-color.brand}",
        },
        name: "marqueeBackgroundColorBrand",
        attributes: {
          category: "marquee",
          type: "background-color",
          item: "brand",
        },
        path: ["marquee", "background-color", "brand"],
      },
    },
    "font-color": {
      brand: {
        key: "{marquee.font-color.brand}",
        $value: "#ffffff",
        $type: "color",
        $description: "",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{white}",
          $type: "color",
          $description: "",
          key: "{marquee.font-color.brand}",
        },
        name: "marqueeFontColorBrand",
        attributes: {
          category: "marquee",
          type: "font-color",
          item: "brand",
        },
        path: ["marquee", "font-color", "brand"],
      },
    },
    "border-radius": {
      desktop: {
        key: "{marquee.border-radius.desktop}",
        $value: "40",
        $type: "borderRadius",
        $description: "",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{border-radius.md}",
          $type: "borderRadius",
          $description: "",
          key: "{marquee.border-radius.desktop}",
        },
        name: "marqueeBorderRadiusDesktop",
        attributes: {
          category: "marquee",
          type: "border-radius",
          item: "desktop",
        },
        path: ["marquee", "border-radius", "desktop"],
      },
      mobile: {
        key: "{marquee.border-radius.mobile}",
        $value: "16",
        $type: "borderRadius",
        $description: "",
        filePath: "src/styles/data-tokens/components/marquee.json",
        isSource: true,
        original: {
          $value: "{border-radius.sm}",
          $type: "borderRadius",
          $description: "",
          key: "{marquee.border-radius.mobile}",
        },
        name: "marqueeBorderRadiusMobile",
        attributes: {
          category: "marquee",
          type: "border-radius",
          item: "mobile",
        },
        path: ["marquee", "border-radius", "mobile"],
      },
    },
  },
  "border-radius": {
    md: {
      key: "{border-radius.md}",
      $value: "40",
      $type: "borderRadius",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/bordeRadius.json",
      isSource: true,
      original: {
        $value: "40",
        $type: "borderRadius",
        $description: "",
        key: "{border-radius.md}",
      },
      name: "borderRadiusMd",
      attributes: {
        category: "border-radius",
        type: "md",
      },
      path: ["border-radius", "md"],
    },
    sm: {
      key: "{border-radius.sm}",
      $value: "16",
      $type: "borderRadius",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/bordeRadius.json",
      isSource: true,
      original: {
        $value: "16",
        $type: "borderRadius",
        $description: "",
        key: "{border-radius.sm}",
      },
      name: "borderRadiusSm",
      attributes: {
        category: "border-radius",
        type: "sm",
      },
      path: ["border-radius", "sm"],
    },
  },
  "powerfull-orange": {
    key: "{powerfull-orange}",
    $value: "#ff602f",
    $type: "color",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/colors.json",
    isSource: true,
    original: {
      $value: "#ff602f",
      $type: "color",
      $description: "",
      key: "{powerfull-orange}",
    },
    name: "powerfullOrange",
    attributes: {
      category: "powerfull-orange",
    },
    path: ["powerfull-orange"],
  },
  dark: {
    key: "{dark}",
    $value: "#232121",
    $type: "color",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/colors.json",
    isSource: true,
    original: {
      $value: "#232121",
      $type: "color",
      $description: "",
      key: "{dark}",
    },
    name: "dark",
    attributes: {
      category: "dark",
    },
    path: ["dark"],
  },
  white: {
    key: "{white}",
    $value: "#ffffff",
    $type: "color",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/colors.json",
    isSource: true,
    original: {
      $value: "#fff",
      $type: "color",
      $description: "",
      key: "{white}",
    },
    name: "white",
    attributes: {
      category: "white",
    },
    path: ["white"],
  },
  "powerfull-blue": {
    key: "{powerfull-blue}",
    $value: "#3200f2",
    $type: "color",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/colors.json",
    isSource: true,
    original: {
      $value: "#3200f2",
      $type: "color",
      $description: "",
      key: "{powerfull-blue}",
    },
    name: "powerfullBlue",
    attributes: {
      category: "powerfull-blue",
    },
    path: ["powerfull-blue"],
  },
  "font-size": {
    xs: {
      key: "{font-size.xs}",
      $value: "16px",
      $type: "fontSizes",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "16px",
        $type: "fontSizes",
        $description: "",
        key: "{font-size.xs}",
      },
      name: "fontSizeXs",
      attributes: {
        category: "font-size",
        type: "xs",
      },
      path: ["font-size", "xs"],
    },
    sm: {
      key: "{font-size.sm}",
      $value: "25.888px",
      $type: "fontSizes",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "{font-size.xs}*1.618",
        $type: "fontSizes",
        $description: "",
        key: "{font-size.sm}",
      },
      name: "fontSizeSm",
      attributes: {
        category: "font-size",
        type: "sm",
      },
      path: ["font-size", "sm"],
    },
    xxs: {
      key: "{font-size.xxs}",
      $value: "9.8888px",
      $type: "fontSizes",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "{font-size.xs}/1.618",
        $type: "fontSizes",
        $description: "",
        key: "{font-size.xxs}",
      },
      name: "fontSizeXxs",
      attributes: {
        category: "font-size",
        type: "xxs",
      },
      path: ["font-size", "xxs"],
    },
    md: {
      key: "{font-size.md}",
      $value: "41.8868px",
      $type: "fontSizes",
      $description: "",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "{font-size.sm}*1.618",
        $type: "fontSizes",
        $description: "",
        key: "{font-size.md}",
      },
      name: "fontSizeMd",
      attributes: {
        category: "font-size",
        type: "md",
      },
      path: ["font-size", "md"],
    },
    lg: {
      key: "{font-size.lg}",
      $value: "67.7728px",
      $type: "fontSizes",
      $description: "for creative title",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "{font-size.md}*1.618",
        $type: "fontSizes",
        $description: "for creative title",
        key: "{font-size.lg}",
      },
      name: "fontSizeLg",
      attributes: {
        category: "font-size",
        type: "lg",
      },
      path: ["font-size", "lg"],
    },
    xl: {
      key: "{font-size.xl}",
      $value: "109.6564px",
      $type: "fontSizes",
      $description: "for creative title",
      filePath: "src/styles/data-tokens/foundation/fontSize.json",
      isSource: true,
      original: {
        $value: "{font-size.lg}*1.618",
        $type: "fontSizes",
        $description: "for creative title",
        key: "{font-size.xl}",
      },
      name: "fontSizeXl",
      attributes: {
        category: "font-size",
        type: "xl",
      },
      path: ["font-size", "xl"],
    },
  },
  xs: {
    key: "{xs}",
    $value: "8px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{xxs}*2",
      $type: "spacing",
      $description: "",
      key: "{xs}",
    },
    name: "xs",
    attributes: {
      category: "xs",
    },
    path: ["xs"],
  },
  md: {
    key: "{md}",
    $value: "16px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{xs}*2",
      $type: "spacing",
      $description: "",
      key: "{md}",
    },
    name: "md",
    attributes: {
      category: "md",
    },
    path: ["md"],
  },
  "3xl": {
    key: "{3xl}",
    $value: "48px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{lg}*2",
      $type: "spacing",
      $description: "",
      key: "{3xl}",
    },
    name: "3xl",
    attributes: {
      category: "3xl",
    },
    path: ["3xl"],
  },
  "4xl": {
    key: "{4xl}",
    $value: "64px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{xl}*2",
      $type: "spacing",
      $description: "",
      key: "{4xl}",
    },
    name: "4xl",
    attributes: {
      category: "4xl",
    },
    path: ["4xl"],
  },
  "2xl": {
    key: "{2xl}",
    $value: "40px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{lg}*1.5 + {xxs}",
      $type: "spacing",
      $description: "",
      key: "{2xl}",
    },
    name: "2xl",
    attributes: {
      category: "2xl",
    },
    path: ["2xl"],
  },
  lg: {
    key: "{lg}",
    $value: "24px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{sm}*2",
      $type: "spacing",
      $description: "",
      key: "{lg}",
    },
    name: "lg",
    attributes: {
      category: "lg",
    },
    path: ["lg"],
  },
  xxs: {
    key: "{xxs}",
    $value: "4px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "4px",
      $type: "spacing",
      $description: "",
      key: "{xxs}",
    },
    name: "xxs",
    attributes: {
      category: "xxs",
    },
    path: ["xxs"],
  },
  xl: {
    key: "{xl}",
    $value: "32px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{md}*2",
      $type: "spacing",
      $description: "",
      key: "{xl}",
    },
    name: "xl",
    attributes: {
      category: "xl",
    },
    path: ["xl"],
  },
  "5xl": {
    key: "{5xl}",
    $value: "80px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{2xl}*2",
      $type: "spacing",
      $description: "",
      key: "{5xl}",
    },
    name: "5xl",
    attributes: {
      category: "5xl",
    },
    path: ["5xl"],
  },
  sm: {
    key: "{sm}",
    $value: "12px",
    $type: "spacing",
    $description: "",
    filePath: "src/styles/data-tokens/foundation/spacing.json",
    isSource: true,
    original: {
      $value: "{xs}*1.5",
      $type: "spacing",
      $description: "",
      key: "{sm}",
    },
    name: "sm",
    attributes: {
      category: "sm",
    },
    path: ["sm"],
  },
};
