// Auto-generated by scripts/generate-tokens.js. Do not edit directly.
export const tailwindTheme = {
  "colors": {
    "powerfull-orange": "#ff602f",
    "dark": "#232121",
    "white": "#ffffff",
    "powerfull-blue": "#3200f2"
  },
  "spacing": {
    "xs": "0.5rem",
    "md": "1rem",
    "3xl": "3rem",
    "4xl": "4rem",
    "2xl": "2.5rem",
    "lg": "1.5rem",
    "xxs": "0.25rem",
    "xl": "2rem",
    "5xl": "5rem",
    "sm": "0.75rem"
  },
  "fontSize": {
    "xs": "1rem",
    "sm": "1.618rem",
    "xxs": "0.618rem",
    "md": "2.6179rem",
    "lg": "4.2358rem",
    "xl": "6.8535rem"
  },
  "borderRadius": {
    "md": "2.5rem",
    "sm": "1rem"
  }
};

export const daisyThemes = [
  {
    "qalim": {
      "primary": "#3200f2",
      "primary-content": "#ffffff",
      "secondary": "#ff602f",
      "secondary-content": "#ffffff",
      "accent": "#ff602f",
      "neutral": "#232121",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#232121",
      "base-300": "#232121",
      "base-content": "#232121",
      "info": "#3200f2",
      "success": "#3200f2",
      "warning": "#ff602f",
      "error": "#ff602f",
      "--rounded-box": "2.5rem",
      "--rounded-btn": "1rem",
      "--rounded-badge": "1rem"
    }
  }
];
