// Auto-generated by scripts/generate-tokens.js. Do not edit directly.
export const tailwindTheme = {
  "colors": {
    "powerfull-orange": "#ff602f",
    "dark": "#232121",
    "white": "#ffffff",
    "powerfull-blue": "#3200f2"
  },
  "spacing": {
    "xs": "0.5000rem",
    "md": "1.0000rem",
    "3xl": "3.0000rem",
    "4xl": "4.0000rem",
    "2xl": "2.5000rem",
    "lg": "1.5000rem",
    "xxs": "0.2500rem",
    "xl": "2.0000rem",
    "5xl": "5.0000rem",
    "sm": "0.7500rem"
  },
  "fontSize": {
    "xs": "1.0000rem",
    "sm": "1.6250rem",
    "xxs": "0.6250rem",
    "md": "2.6250rem",
    "lg": "4.2500rem",
    "xl": "6.8750rem"
  },
  "borderRadius": {
    "md": "2.5000rem",
    "sm": "1.0000rem"
  }
};

export const daisyThemes = [
  {
    "qalim": {
      "primary": "#3200f2",
      "primary-content": "#ffffff",
      "secondary": "#ff602f",
      "secondary-content": "#ffffff",
      "accent": "#ff602f",
      "neutral": "#232121",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-200": "#232121",
      "base-300": "#232121",
      "base-content": "#232121",
      "info": "#3200f2",
      "success": "#3200f2",
      "warning": "#ff602f",
      "error": "#ff602f",
      "--rounded-box": "2.5000rem",
      "--rounded-btn": "1.0000rem",
      "--rounded-badge": "1.0000rem"
    }
  }
];
